<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            [
                'id'    => 0,
                'name' => 'RK-Malle lokaal beneden',
                'description' =>null,
                'street' => 'Turnhoutsebaan',
                'number' => '8',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'RK-Malle garage',
                'description' =>null,
                'street' => 'Turnhoutsebaan',
                'number' => '8',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'RK-Malle groot leslokaal boven',
                'description' =>null,
                'street' => 'Turnhoutsebaan',
                'number' => '8',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Online',
                'description' =>null,
                'street' => null,
                'number' => null,
                'zip' => null,
                'city' => null,
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Vliegveld Malle',
                'description' =>null,
                'street' => 'Heihuizen',
                'number' => '8',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Domein de Renesse',
                'description' =>null,
                'street' => 'Lierselei',
                'number' => '30',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Chiro Oostmalle/Jeugdhuis Malmejo',
                'description' => 'Achter Notelaar',
                'street' => 'Lierselei',
                'number' => '19',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Salphen',
                'description' =>null,
                'street' => 'Salphen',
                'number' => null,
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'KSA Westmalle',
                'description' =>null,
                'street' => 'Berckhovenstraat',
                'number' => '23',
                'zip' => '2390',
                'city' => 'Westmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Piste Mariaagaarde',
                'description' =>null,
                'street' => 'Grootakker',
                'number' => null,
                'zip' => '2390',
                'city' => 'Westmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Maris Stella Instituut',
                'description' =>null,
                'street' => 'Antwerpsesteenweg',
                'number' => '67',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Mariagaarde Instituut',
                'description' =>null,
                'street' => 'Oude Molenstraat',
                'number' => '13',
                'zip' => '2390',
                'city' => 'Westmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Mintjens Arena',
                'description' =>null,
                'street' => 'Heidemolenbaan',
                'number' => '75',
                'zip' => '2390',
                'city' => 'Westmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Antwerpsesteenweg',
                'description' =>null,
                'street' => 'Antwerpsesteenweg',
                'number' => null,
                'zip' => '2390',
                'city' => 'Westmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Gemeentelijke Sporthal Berckhoven',
                'description' =>null,
                'street' => 'Berckhovenstraat',
                'number' => '25',
                'zip' => '2390',
                'city' => 'Westmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'De Notelaar',
                'description' =>null,
                'street' => 'Lierselei',
                'number' => '15',
                'zip' => '2390',
                'city' => 'Oostmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Parochiezaal Westmalle',
                'description' =>null,
                'street' => 'Sint Jozeflei',
                'number' => '27',
                'zip' => '2390',
                'city' => 'Westmalle',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Sportpaleis Antwerpen',
                'description' =>null,
                'street' => 'Schijnpoortweg',
                'number' => '119',
                'zip' => '2170',
                'city' => 'Merksem',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'RAFC Bosuilstadion',
                'description' => 'Zie OO voor exacte locatie/RV punt',
                'street' => 'Oude Bosuilbaan',
                'number' => '54',
                'zip' => '2100',
                'city' => 'Deurne',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Centrum Bornem',
                'description' => 'Zie OO voor exacte locatie/RV punt',
                'street' => null,
                'number' => null,
                'zip' => '2880',
                'city' => 'Bornem',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Festivalweide Rock Werchter',
                'description' => 'Zie OO voor exacte locatie/RV punt',
                'street' => 'Haachtsesteenweg',
                'number' => null,
                'zip' => '3118',
                'city' => 'Rotselaar',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Festivalweide Graspop',
                'description' => 'Zie OO voor exacte locatie/RV punt',
                'street' => 'Kastelsedijk',
                'number' => null,
                'zip' => '2480',
                'city' => 'Dessel',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'MotoCross Lille',
                'description' =>null,
                'street' => 'Rooverstraat',
                'number' => null,
                'zip' => '2275',
                'city' => 'Lille',
                'created_by_id' => 1,
            ],
            [
                'id'    => 0,
                'name' => 'Festivalweide Sunrise',
                'description' => 'Zie OO voor exacte locatie/RV punt',
                'street' => 'Strandweg',
                'number' => 6,
                'zip' => '2275',
                'city' => 'Lille',
                'created_by_id' => 1,
            ]
        ];

        Location::insert($locations);
    }
}
